echo "Download all remote resources to local-repositories"
git clone --progress -v "https://github.com/MechatronicBeing/resources.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-calculating.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-counting.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-drawing.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-engineering.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-evaluating.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-exploring.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-learning.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-listening.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-playing-games.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-reading.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-translating.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-writing.git"
