## Repositories in <https://github.com/MechatronicBeing/resources>
[Calculating](https://github.com/MechatronicBeing/resources-calculating/)  
[Counting](https://github.com/MechatronicBeing/resources-counting/)  
[Drawing](https://github.com/MechatronicBeing/resources-drawing/)  
[Evaluating](https://github.com/MechatronicBeing/resources-evaluating/)  
[Learning](https://github.com/MechatronicBeing/resources-learning/)  
[Listening](https://github.com/MechatronicBeing/resources-listening/)  
[Reading](https://github.com/MechatronicBeing/resources-reading/)  
[Translating](https://github.com/MechatronicBeing/resources-translating/)  
[Writing](https://github.com/MechatronicBeing/resources-writing/)  
